### ISSUE TITLE
Salesforce error - InvalidJob: Unable to parse Job

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#113]
## Bug
See [run failure](https://www.openfn.org/projects/lwala-chw-support/runs/064a5156-cf89-7824-9add-ea8a0b80419a) with error `InvalidJob: Unable to parse Job`. 

The client _thinks_ the data import to Salesforce is succeeding, and yet we're getting this error from the Salesforce API. What do you think is going on? 

## expression
https://github.com/OpenFn/lwala/blob/master/bulk/bulkUpsert-Person.js

### adaptor 
`@openfn/language-salesforce@3.0.7`

## state
- config: `Lwala Partial Sandbox (May 2023 - Bulk)`
- data: [Run WF1 job ](https://github.com/OpenFn/lwala/blob/master/bulk/bulkGetCases-Person.js) to generate state for this job

**Comment by aleksa-krolls** [comment]
@mtuchi can you check this out later today? 
cc @daissatou2

**Comment by mtuchi** [comment]
@aleksa-krolls what is the status for this issue ? cc @daissatou2

**Comment by aleksa-krolls** [comment]
No response from the client with confirmation that they want us to take action here. Abandoning for now.
