### ISSUE TITLE
Commcare credentials clean-up

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/lwala#121]
### Summary
The [Q3 2022] **Update HH Name in CommCare** `salesforce-commcare-jobs/Update-HH-Name.js` job is failing with a `401` Unauthorized error.  We lost track of which credential was used before and the newly created credential is not working either 

[See the last run failure here ](https://www.openfn.org/projects/lwala-chw-support/runs/065a6a64-841f-73c8-9e29-ba8ce22352bc)

### Todo's
- [ ] Clean up unused credentials on `Lwala CHW Support`
- [x] Create new commcare credential for `Update HH Name in CommCare` job

**Comment by mtuchi** [comment]
Hey @hngondoki , Nice job on  getting the new commcare credential for `Update HH Name` job working. Can you also check all unused credentials on `Lwala CHW Support` project and propose a clean-up ?

**Comment by aleksa-krolls** [comment]
@mtuchi we're going to address this as we migrate to v2, so moving to icebox for now - but I will own this.
