### ISSUE TITLE
Values returning undefined when using dataPath()

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#16]
Can you please help me? :-)  Lwala wants to add logic to create child "Deceased" Person record(s) if they specify on the Household form that there have been deaths. 

I've drafted these [lines #197-251](https://github.com/OpenFn/lwala/blob/76f168e33230eff6bf4cd258a0ae8cddbb989324/commcare-salesforce-jobs/MOH513-Enroll-Household-in-SF.js#L197-L251). It was mostly a copy/paste task from another job, but I'm finding that values are returning undefined when trying to make use of the `dataPath()` helper. For example: 

**Actual Behavior**
I find L236 `field("Dead_age__c", dataValue("age_dead"))` and other CC values that appear under the `dataPath("$.form.household_deaths.deaths[*]")` are returning undefined/ null. If testing this job against this [updateHHnew.json](https://github.com/OpenFn/lwala/blob/deceased_person/sample_data/updateHHnew.json), I get the output: 
```
Upserting Person__c with externalId CommCare_ID__c : { CommCare_ID__c: '7cba8aa8-0a0d-440a-9e6a-8b15a9ab742cundefined',
  CommCare_HH_Code__c: '7cba8aa8-0a0d-440a-9e6a-8b15a9ab742c',
  RecordType: { Name: false },
  Name: 'Deceased Person',
  Source__c: true,
  Catchment__r: { Name: 'East Kamagambo' },
  Client_Status__c: 'Deceased',
  Dead_age__c: undefined,
  Cause_of_Death__c: null,
  Verbal_autopsy__c: undefined,
  Active_in_Thrive_Thru_5__c: 'No',
  Active_in_HAWI__c: 'No',
  Active_TT5_Mother__c: 'No',
  TT5_Mother_Registrant__c: 'No',
  Date_of_Death__c: '2020-04-02',
  Inactive_Date__c: '2020-04-02' }
Finished.
```
**Expected Behavior**
I expect L236 `field("Dead_age__c", dataValue("age_dead"))` and other CC mappings that appear under the `dataPath("$.form.household_deaths.deaths[*]")` to NOT return null. 
```
Upserting Person__c with externalId CommCare_ID__c : { CommCare_ID__c: '7cba8aa8-0a0d-440a-9e6a-8b15a9ab742c60',
  CommCare_HH_Code__c: '7cba8aa8-0a0d-440a-9e6a-8b15a9ab742c',
  RecordType: { Name: 'Mother' },
  Name: 'Deceased Person',
  Source__c: true,
  Catchment__r: { Name: 'East Kamagambo' },
  Client_Status__c: 'Deceased',
  Dead_age__c: '60',
  Cause_of_Death__c: 'Accident Injury',
  Verbal_autopsy__c: 'Yes',
  Active_in_Thrive_Thru_5__c: 'No',
  Active_in_HAWI__c: 'No',
  Active_TT5_Mother__c: 'No',
  TT5_Mother_Registrant__c: 'No',
  Date_of_Death__c: '2020-04-02',
  Inactive_Date__c: '2020-04-02' }
Finished.
```

**To Test...**
1. Run this [`MOH513-Enroll-Household-in-SF.js`](https://github.com/OpenFn/lwala/blob/deceased_person/commcare-salesforce-jobs/MOH513-Enroll-Household-in-SF.js#L236) job version (deceased_person branch)
2. State file: [updateHHnew.json](https://github.com/OpenFn/lwala/blob/deceased_person/sample_data/updateHHnew.json)
3. Sandbox creds: Lwala Salesforce Sandbox (see LastPass)

Curious to learn what should be done here! Was referencing a [recent Nalibali example](https://github.com/OpenFn/Nalibali/blob/38528f1bce5708146ababdf2497be50c3c38f116/add-survey.js#L31) with this dataPath() and couldn't identify where I went wrong. Thanks in advance for the support.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 When you have a moment, can you please take a look at this sometime Thursday? I think it should be a quick fix... ty in advance for the guidance!

**Comment by taylordowns2000** [comment]
Heyo. So—it seems that your constant `person` in line 4 is undefined, given that sample state file.
```js
const person = state.data.form.Person;
```
I see no `Person` key in `state.data.form`. This means lines 5-7 create an array of undefined:
```js
[ undefined ]
```.
Later, for every member of that array (just one, `undefined), you're executing the operations and those are probably working out OK, but you don't have the person data you thought you had in there. Looks like this is a workaround because CommCare _sometimes_ sends an object and _sometimes_ sends an array. If that's true, let's figure out where the array appears (look at a sample with more than one person) and use that in line 4.
