### ISSUE TITLE
Modify logic for inserting 'ANC' Services

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#21]
## Overview
Lwala CHWs use CommCare forms for logging different patient visits, incl. antenatal care and immunizations. All data is integrated with Salesforce for centralized reporting. 
### Current Behavior
In the L387-L588, currently the job will upsert "ANC" services in Salesforce when specific criteria is met in CommCare. Due to CommCare configuration changes we want to change this triggering logic. 
https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L387-L588

See below for an example were ANC services are created if a specific checkbox is checked in the CommCare app. We want to change the criteria in these `if()` statements to not rely on the `"copy-to-..."` keys. 
https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L387-L393

## Request
Update `Update-Person-in-SF-Production.js` so that all 5 ANC Service types are upserted when the `"ANCs":{...}"` object and relevant `"ANC_X"` keys (see list below) are available in the CommCare Message payload. 

1. `ANC_1`- [See L388](https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L388)
2. `ANC_2`- [See L528](https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L528)
3. `ANC_3` - [See L468](https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L468)
5. `ANC_4` - [See L508](https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L508)
5. `ANC_5` - [See L548](https://github.com/OpenFn/lwala/blob/0e043d0eae6f1708afda43ea5326e2471e81ef15/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L548)

### Example
The below sample state meets the following criteria: 
1. `"ANCs":{...}` object is present in payload && not undefined
2. `"ANC_4"` not undefined && not null
```
"form": {
    "#type": "data",
    "TT5": {
      "Child_Information": {
        "ANCs": {
          "ANC_4": "2020-09-03",
          "EDD_Label": "OK",
          "Facility4": "Other",
          "anc_1": "OK",
          "anc_2": "OK",
          "anc_3": "OK",
          "copy-2-of-anc_3": "click_to_enter_anc_3",
          "copy-3-of-anc_3": ""
        },
```
Therefore the job should --> upsert 1 "ANC_4" Service record.  

### state.json
Test with Lwala Salesforce sandbox. See LP for creds. 
1. Use `sample_data/state_anc4.json` to test scenario where all 5 ANC Services should be inserted in Salesforce
2. Use `sample_data/state_noanc.json` to test scenario where NO ANC Services should be inserted 
### adaptor
Use language-salesforce and make use of this LP's `FakeAdaptor` for offline testing. 
### expression.js
Update `Update-Person-in-SF-Production.js`

## Toggl
Log your time to [Lwala Cleanup 2020](https://track.toggl.com/3335160/projects/163379269/team)

**Comment by lakhassane** [comment]
Closing since it has been solved and merged.

**Comment by aleksa-krolls** [comment]
@lakhassane Currently this job fails with `TypeError [Error]: Cannot destructure property 'ANCs'` when run against `sample_data/state_noanc2.json`. I think this is because `"TT5.Child_Information"` is not present for mother patients. 

We need to update `Update-Person-in-SF-Production.js` to handle payloads where only `Mother_Information`, and no `Child_Information` or `ANCs`, is present. 
```
"TT5": {
      "Mother_Information": {
        "Pregnant": "No",
        "confirmed_delivery": "No",
        "continuous_pnc_visits_4_days": "0",
        "continuous_pregnant_women": "",
        "family_planning": "yes",
        "family_planning_method": "injection",
        "pnc_visits_4_days": "0",
        "previous_pnc_visits_4_days": "0",
        "previous_pregnant_woment": "Yes"
      }
```
