### ISSUE TITLE
Modify logic for inserting Immunization Services

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#22]
## Overview
This request is very similar to issue #21 but related to Immunization Services instead of ANC.  
### Current Behavior
In the L589-L940, currently the job will upsert Immunization services in Salesforce when specific criteria is met in CommCare. Due to CommCare configuration changes we want to change this triggering logic. 
https://github.com/OpenFn/lwala/blob/d9732bebca39f76ae52a539b22f268aeb90b3b69/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L589-L940

We again want to change the criteria in these `if()` statements to not rely on the `"click-to-enter..."` keys. 

## Request
Update `Update-Person-in-SF-Production.js` so that all 8 Immunization Service types are upserted when the `"Immunizations":{...}"` object and relevant **Immunization Type** key (see list below) are available in the CommCare Message payload. 

1. `BCG_h` if there is a date --> create a "BCG" Service
2. `OPV0_h`
3. `OPV1_h`
4. `OPV2_h`
5. `OPV3_h`
6. `Measles6_h`
7. `Measles9_h`
8. `Measles18_h`

### Example
The below sample state meets the following criteria: 
1. `"Immunizations":{...}` object is present in payload && not undefined
2. `"BCG_h"` not undefined && not null
3. `"OPV0_h"` not undefined && not null
```
 "Immunizations": {
          "BCG_h": "2019-10-28",
          "Facility_OPV_0": "Lwala_Hospital",
          "Fully_Immunized": "No",
          "Measles18_h": "",
          "Measles6_h": "",
          "Measles9_h": "",
          "OPV0_h": "2019-10-28",
          "OPV1_h": "",
          "OPV2_h": "",
          "OPV3_h": "",
          "OPV_0": "2019-10-28",
          "anc_3": "click_to_enter_anc_3",
          "bcg_bcg": "OK",
          "continuous_children_not_fully_immunized": "1",
          "copy-1-of-anc_3": "",
          "copy-2-of-anc_3": "",
          "copy-4-of-anc_3": "",
          "copy-5-of-anc_3": "",
          "copy-6-of-anc_3": "",
          "copy-7-of-anc_3": "",
          "previous_children_not_fully_immunized": "0"
        },
```
Therefore the job should --> upsert 2 Service records, 1 for "BCG" and 1 for "OPV0" . 

### state.json
Test with Lwala Salesforce sandbox. See LP for creds. 
1. Use `sample_data/state_immunizations.json` to test scenario where 5 Immunization Services (BCG and all 4 OPV) should be inserted in Salesforce
2. Use `sample_data/state_immunizations2.json` to test scenario where 3 Services (Measles 6, 9, 18) should be inserted 
3. Use `state_Noimmunizations.json` to test scenario where NO Immunization services should be inserted. 

### adaptor
Use language-salesforce and make use of this LP's `FakeAdaptor` for offline testing. 
### expression.js
Update `Update-Person-in-SF-Production.js`

## Toggl
Log your time to [Lwala Cleanup 2020](https://track.toggl.com/3335160/projects/163379269/team)

**Comment by lakhassane** [comment]
Closing since it has been solved and merged.
