### ISSUE TITLE
Supervisor Visit mapping logic

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#25]
## Overview
We need to clean & re-format picklist values provided by CommCare before uploading to Salesforce.  This logic needs to be applied in 2 jobs wherever the Salesforce field `Supervisor_Visit__c` is referenced. 

https://github.com/OpenFn/lwala/blob/642bf02a3f03604a070a969d1dfef468eb166454/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L1420-L1424

https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH513-Update-Household-in-SF-Production.js#L46-L63

## Request
Update `Update-Person-in-SF-Production.js` and `MOH513-Update-Household-in-SF-Production.js` to include the following mappings for wherever `Supervisor_Visit__c` is referenced: 
```
// commcare_input: salesforce_output
// "supervisor_visit": "Supervisor_Visit__c"
'community_health_nurse': 'Community Health Nurse'
'chw_supervisor': 'CHW Supervisor'
'chewschas': 'CHEWs/CHAs'
'other': 'Other'
'none': 'None'
```

### Example
The below sample state from CommCare should output the value `'CHEWs/CHAs'` in Salesforce. 
```
    "supervisor_visit": "chewschas"
```

### state.json
Test with Lwala Salesforce sandbox. See LP for creds. 
1. `Update-Person-in-SF-Production.js` test: Use `sample_data/state_anc4.json` to test scenario where `Supervisor_Visit__c = 'None'`. Update the value ` "supervisor_visit": ______` to test the different combinations. 
2. `MOH513-Update-Household-in-SF-Production.js` test: Use `sample_data/state_HHsupervisor.json`

### adaptor
Use language-salesforce and make use of this LP's `FakeAdaptor` for offline testing. 
### expression.js
Update `Update-Person-in-SF-Production.js`
Update `MOH513-Update-Household-in-SF-Production.js`

## Toggl
Log your time to [Lwala Cleanup 2020](https://track.toggl.com/3335160/projects/163379269/team)

**Comment by aleksa-krolls** [comment]
@lakhassane Can you please add logic to handle for instances where `supervisor_visit` is null or undefined? If so, it should return a null value.

**Comment by lakhassane** [comment]
@aleksa-krolls added the logic and made a test.
First screen shows an undefined `supervisor_visit` and second one shows the ouput where it is set to `null`
![image](https://user-images.githubusercontent.com/8411231/93089007-3565b880-f68a-11ea-85af-1d15280ada03.png)

![image](https://user-images.githubusercontent.com/8411231/93089047-41ea1100-f68a-11ea-9105-5a9572e6197e.png)

**Comment by lakhassane** [comment]
Closing this as it is solved.
