### ISSUE TITLE
TypeError [Error]: Cannot read property 'Child_Information' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#32]
A new error has surfaced in this Update Person job we've recently made changes in as part of issues #21 and #22. See run [failure here](https://www.openfn.org/projects/185/runs/9828973). 
`TypeError [Error]: Cannot read property 'Child_Information' of undefined`

### Specific request
Can you please troubleshoot and make the appropriate changes as needed? We need to handle different types of state for this CommCare form where the `Child_Information` object might not at all be present in the JSON Message payload. 

### state.json
Use `sample_data/state_noChildInfo.json`. 

### adaptor
language-salesforce

### expression.js
`Update-Person-in-SF-Production.js`

### Toggl
Lwala Cleanup Project

**Comment by lakhassane** [comment]
Closing this as it is solved.
