### ISSUE TITLE
Change Lwala project concurrency to 1

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#40]
Several times per day, runs fail because of the Salesforce `UNABLE_TO_LOCK_ROW` error ([see example here](https://www.openfn.org/projects/185/runs/9977480)). This is due to Salesforce-side automation that assigns a UID to new records we create and this Apex trigger is not bulkified. To circumvent this, I'd like to try bulk testing when Lwala's OpenFn project (id `185`) concurrency is dialed down to 1. 

We're nearly finished with testing and almost ready to initiate the big CommCare-Salesforce resync, but I'd like to make sure we sort this out before running a massive bulk set of runs. Let me know when ready to test, thanks!

**Comment by taylordowns2000** [comment]
This is being addressed here: https://github.com/taylordowns2000/platform-app/issues/982

**Comment by taylordowns2000** [comment]
This is now available on staging. Will deploy to production shortly. Closing issue now as it's been set manually on prod in the interim.
