### ISSUE TITLE
Fetch Lwala historical forms via API

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#41]
## Background
We're helping Lwala fix several bugs in their jobs that have caused data quality issues in the CommCare-Salesforce integration. Now that the bugs have been addressed and new mapping changes implemented, Lwala wants to re-sync its historical CommCare data with Salesforce via OpenFn. We're finding that the manual way to achieve this is going to take way too long, so they'd like to automate this process. 

## The request
Create a new job that: 
1. Fetches historical form data by sending a GET request to the CommCare endpoint `https://www.commcarehq.org/a/lwala-community-alliance/api/v0.5/form/`. 
2. Posts each individual form from the GET response back to the OpenFn inbox (so that the existing jobs can be used to re-process these forms)

Notes: 
- Total form count is **697,241**. CommCare API limits each response to 1000 forms/ request. 
- Therefore I'm wondering if we can add a date cursor (i.e., `received_on_start=2012-01-01`) that starts on `2018-01-01` and checks for every day?
- Given the data volumes, I'm wondering if this should be run locally? 
- **TEST LOCALLY only for now... we do _NOT_ want to post anything to the real inbox yet**

## state.json
See LP credential notes - search for Lwala CommCare. 
See CommCare API docs for [List Forms](https://confluence.dimagi.com/display/commcarepublic/List+Forms). 

## expression.js
Please create a new `getForms.js` job to be run on-demand. 

## adaptor
`language-http` 

## output
See `sample_data/commcareListForms.json` for a sample response to a GET request made to the `/form` endpoint. 
Every object within the `"objects":[...]` is an individual form that should be posted back to the OpenFn inbox. 

## side effects
Running this new job should fetch historical forms and post back each individual form as a new message to [the Lwala inbox](https://www.openfn.org/projects/185/messages).

**Comment by taylordowns2000** [comment]
Using limit and offset, we could crawl through these all until there were none left.
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/3a23c1e9-bf2c-4bc9-ab58-2c02f95e7595)

**Comment by taylordowns2000** [comment]
This is set up (https://openfn.org/projects/185/jobs/3637) but shouldn't be run until a discussion about bulk is had with Lwala. Not counting the time it takes to fetch data from CommCare and post it back to OpenFn using individual requests (maybe 1-2s per form?), if we assume that each submission to Salesforce takes ~5 seconds and that we cannot either use a bulk API or run these requests concurrently (because of the trigger designs in Salesforce), then we're talking 40.5 days to load 700,000 forms from CommCare.

**Comment by taylordowns2000** [comment]
Closing as we've chosen to reprocess from OpenFn.org instead of re-fetching old data.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I've modified the parameter and want to run this for a specific form. Questions: 
1. What does my credential need to look like? Do I need to have the Inbox ID? 
2. How does L19 need to be updated to remove the reference to the local host?

**Comment by taylordowns2000** [comment]
Great. (1) Should look like this:
```json
{
    "baseUrl": "https://www.commcarehq.org",
    "username": "aleksa@verasolutions.org",
    "password": "somethingSecret",
    "openfnInboxUrl": "someSecretUUId"
  }
```
(2) `L19` should be updated to use the `baseUrl` of whichever _server_ you're running the jobs on. If it's OpenFn's US-based production servers then it should read:
```js
state.configuration = { baseUrl: 'https://www.openfn.org' };
```
