### ISSUE TITLE
TypeError [Error]: Cannot read property 'supervisor_visit' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#42]
## Bug
See [run failure here](https://www.openfn.org/projects/185/runs/10144605) with the error `TypeError [Error]: Cannot read property 'supervisor_visit' of undefined`. This is related to the below lines in the job `Update-Person-in-SF-Production.js`.  
https://github.com/OpenFn/lwala/blob/6542f1ca2fedfc402a1d7e1b29e5def418ff46bb/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L1417-L1419

## state.json
See LP for Lwala Sandbox credentials. Use [this message](https://www.openfn.org/projects/185/messages/9687990) for state - but do NOT upload to Github (it contains real data). 

On L10 on this message, you'll see that `"supervisor_visit": "none",`. 

## adaptor 
`language-salesforce`

## output.json
This should successfully create a `Visit__c` record where `Supervisor_Visit__c = 'None'`. 

When you've implemented the change, re-run the job for [this message](https://www.openfn.org/projects/185/messages/9687990) to see a successful run.

**Comment by lakhassane** [comment]
@aleksa-krolls check here please and let me know how the run on prod goes. If it works we might need to change the other job for lwala before we get on that issue again (which I'm convinced we will).
