### ISSUE TITLE
Incorrect transformation in Enroll Household job

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lwala#49]
# Request
1. There is a transformation error in the [MOH513 Enroll Household job](https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH513-Enroll-Household-in-SF.js).

In [this message](https://www.openfn.org/projects/pdbmj5/messages/m4prdz8m) on `line 102` we recieve the following value:
 `"No_FPmethod_reason": "intentions_of_getting_pregnant"`. This should be transformed to `Intentions of getting pregnant` but the erroneous result is `'intentions of getting The client is pregnant'`. 

**Transformation rules**:
`pregnant` --> `The client is pregnant`
`intentions_of_getting_pregnant` --> `Intentions of getting pregnant`
`lack_of_access_to_fp_information` > `Lack of access to FP information`

i think the problem lies [in this piece of code](https://github.com/OpenFn/lwala/blob/283dbb67b0b897d379a54cae75b5af90b16211c8/commcare-salesforce-jobs/MOH513-Enroll-Household-in-SF.js#L226) where we replace the word `pregnant` but not checking for whole word. So we're picking up `pregnant` from `intentions_of_getting_pregnant`. 

2. Also please add: `intentions_of_getting_pregnant` and ``lack_of_access_to_fp_information` (see Transformation rules above) to the job (they were probably added later to CommCare hence the problem and missing cleaning).

# Expression
Job: https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH513-Enroll-Household-in-SF.js

# Failed run to test: https://www.openfn.org/projects/pdbmj5/runs/rj5jrm6z
Message: https://www.openfn.org/projects/pdbmj5/messages/m4prdz8m

# State: 
See LP for `Lwala Salesforce Production`

**Comment by lakhassane** [comment]
@ritazagoni you are ready to go: https://www.openfn.org/projects/pdbmj5/runs/rwag4w44
