### ISSUE TITLE
TypeError [Error]: serviceId.replace is not a function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#58]
## Issue
On recent runs, there is a `TypeError` popping up:  `TypeError [Error]: serviceId.replace is not a function`

Looks like a replace function was implemented to ensure that all back slashes ("`/`") are removed from the custom-generated uuids before syncing to Salesforce. Can you please take a look and make appropriate adjustments? 

Feel free to re-run on platform to see the error & test: https://www.openfn.org/projects/lwala-chw-support/runs/061dd499-7ad6-7585-9dd1-85bbbcfa9d67

## state
Config: See LP for `Lwala Salesforce Production`
https://www.openfn.org/projects/lwala-chw-support/messages/061dd499-71b6-784f-a745-704e1dcfdf3c

## expression
https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH514-Update-Person-in-SF-Production.js

**Comment by lakhassane** [comment]
@aleksa-krolls I solved the issue with serviceId but I'm having this error now: https://www.openfn.org/projects/lwala-chw-support/runs/061deb01-f638-7715-983e-f65d024471d8

Also in this [line](https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH514-Update-Person-in-SF-Production.js#L2695) there is `Clinical_Services_Rendered` that is use as an array but is not an array in the state, is the message used correct?

**Comment by aleksa-krolls** [comment]
Looks like this is data from the new form version & created by `test.2021` user. Following up with the client. 
https://www.openfn.org/projects/lwala-chw-support/messages/061dd499-71b6-784f-a745-704e1dcfdf3c
