### ISSUE TITLE
TypeError [Error]: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/lwala#61]
## Bug
See run failure with error: `TypeError [Error]: Cannot read property 'toString' of undefined`

Feel free to re-run on platform. 

## adaptor
salesforce

## state
Config: Ask Mamadou/See LP for Lwala Salesfoce Sandbox (MOTG - Implementation user)`.

Data: 
https://www.openfn.org/projects/lwala-chw-support/messages/0620e80e-af4c-7eab-901e-3e5714af23c3

## expression
https://github.com/OpenFn/lwala/blob/master/commcare-salesforce-jobs/MOH513-Enroll-Person-in-SF.js

## Expected results
Person record should be successfully upserted. Send me the successful run link if you're able to get it working.

**Comment by lakhassane** [comment]
@aleksa-krolls issue fixed here. Check latest run: https://www.openfn.org/projects/lwala-chw-support/runs/0620fd76-2f4b-7004-a3ba-a7214a9289a2

**Comment by aleksa-krolls** [comment]
@lakhassane what was the issue? Something with date formatting?

**Comment by lakhassane** [comment]
@aleksa-krolls there were a misplace of some `field()`. Instead of putting them in the `fields()` object (the 3rd parameter of the upsert) they were outside, so the upsert had 4 parameters.
